services:
  stock-tracker-api:
    build: ./backend
    ports:
    - "3000:3000"
    environment:
      ALPHAVANTAGE_API_BASE_URL: https://www.alphavantage.co
      ALPHAVANTAGE_API_KEY: REAL_KEY_GOES_HERE